---
title: "WUE_d13_bayes_tables"
author: "Kelly Heilman"
date: "1/7/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
library(reshape2)

```


```{r , results="asis", echo = FALSE}
d13C.samples <- readRDS("/Users/kah/Documents/TreeRings/outputs/growth_model/iWUE_MAP_TMAX_dbh_cohort/full.iso_v3.rds")


d13.df <- d13C.samples %>% group_by(site.code, site, ageclass, structure) %>% summarise(n.tree =length(unique(ID)),
                                                                   n.year =length(unique(year)),
                                                                   
                                                                   d13C = round(mean(Cor.d13C.suess), 2),
                                                                   WUE = round(mean(iWUE), 2))

colnames(d13.df) <- c("Site #", "Site", "Cohort", "Structure", "# Trees", "# Years", "$\\dot{m}_1$",  "Average iWUE")
  
kable(d13.df, "latex",align=c("c", "c", "l", "c", "c", "c"), booktabs = T, caption = "Stable Isotope samples", col.names = c("Site Number", "Site", "Cohort", "Structure", "Number of Trees", "Number of Years", "$\\delta^{13}C$",  "Average iWUE"), escape = FALSE) %>%
kable_styling() %>% collapse_rows(c(1), latex_hline = "major") 
```



```{r , results="asis", echo = FALSE}
# read in the iWUE and d13 cohort model outputs:
# first iWUE:
  WUEparams <- readRDS("/Users/kah/Documents/TreeRings2/outputs/growth_model/iWUE_MAP_TMAX_dbh_cohort/samps.iWUE_age.cohort.re_struct_cohort_scaled_dataset_v4.rds")
samps <- WUEparams[[1]]
WUE <- data.frame(samps [,1:8])
# 1 - Modern, 2 = past
alpha.diff <- ((WUE[,1]-WUE[,2] )/WUE[,2])*100
d13.pct.diff <- data.frame(
  pct.change = mean(alpha.diff),
  Ci.low = quantile(alpha.diff, 0.025), 
  Ci.high = quantile(alpha.diff, 0.975), 
  median = median(alpha.diff))#, 
  #hdi.low = hdi(alpha.diff)[1], 
  #3hdi.high = hdi(alpha.diff)[2])



WUE.m <- reshape2::melt(WUE)
colnames(WUE.m)[1] <- "Var2"
WUE.cohort.summary <- WUE.m %>% group_by(Var2) %>% dplyr::summarise(mean = mean(value), 
                                       ci.lo = quantile(value, 0.025), 
                                       ci.hi = quantile(value, 0.975))
WUE.cohort <- WUE.cohort.summary %>% separate(Var2, into = c("param", "class"))

# create summary tables of WUE coefficients:
WUE.cohort.summary <- WUE.m %>% group_by(Var2) %>% dplyr::summarise(mean = mean(value), 
                                       Ci.low = quantile(value, 0.025), 
                                       Ci.high = quantile(value, 0.975))
WUE.cohort <- WUE.cohort.summary %>% separate(Var2, into = c("param", "class"))



WUE.cohort$Ci.95 <- paste0("(",round(WUE.cohort$Ci.low, 2), " - ", round(WUE.cohort$Ci.high, 2), ")")
WUE.cohort$mean <- round(WUE.cohort$mean, 3)
WUE.cohort$mean <- ifelse(WUE.cohort$Ci.low < 0 & WUE.cohort$Ci.high< 0, paste(WUE.cohort$mean, "*"),
                                  ifelse(WUE.cohort$Ci.low > 0 & WUE.cohort$Ci.high > 0, paste(WUE.cohort$mean, "*"), WUE.cohort$mean))

WUE.cohort$class <- ifelse(WUE.cohort$class %in% 1, "Modern", "Past")
WUE.cohort$param <- ifelse(WUE.cohort$param %in% "beta1", "Baseline intercept", 
                            ifelse(WUE.cohort$param %in% "beta2", "Precip",
                                   ifelse(WUE.cohort$param %in% "beta3", "June Tmax","DBH")))

WUE.cohort <- WUE.cohort[,c("param", "class", "mean", "Ci.95")]



# now d13C
d13Cparams <- readRDS( "/Users/kah/Documents/TreeRings2/outputs/growth_model/iWUE_MAP_TMAX_dbh_cohort/samps.d13_ageclass_struct_cohort_scaled_dataset_v4.rds")
#samps <- d13Cparams[[1]]
d13C <- d13Cparams [,1:8]
# 1 - Modern, 2 = past

d13C.m <- melt(data.frame(d13C))
colnames(d13C.m)[1] <- "Var2"
d13C.cohort.summary <- d13C.m %>% group_by(Var2) %>% dplyr::summarise(mean = mean(value), 
                                       Ci.low = quantile(value, 0.025), 
                                       Ci.high = quantile(value, 0.975))
d13C.cohort <- d13C.cohort.summary %>% separate(Var2, into = c("param", "class"))



d13C.cohort$Ci.95 <- paste0("(",round(d13C.cohort$Ci.low, 2), " - ", round(d13C.cohort$Ci.high, 2), ")")
d13C.cohort$mean <- round(d13C.cohort$mean, 3)
d13C.cohort$mean <- ifelse(d13C.cohort$Ci.low < 0 & d13C.cohort$Ci.high< 0, paste(d13C.cohort$mean, "*"),
                                  ifelse(d13C.cohort$Ci.low > 0 & d13C.cohort$Ci.high > 0, paste(d13C.cohort$mean, "*"), d13C.cohort$mean))

d13C.cohort$class <- ifelse(d13C.cohort$class %in% 1, "Modern", "Past")
d13C.cohort$param <- ifelse(d13C.cohort$param %in% "beta1", "Baseline intercept", 
                            ifelse(d13C.cohort$param %in% "beta2", "Precip",
                                   ifelse(d13C.cohort$param %in% "beta3", "June Tmax","DBH")))

d13C.cohort <- d13C.cohort[,c("param", "class", "mean", "Ci.95")]


# join the tables together:

beta.params <- merge(d13C.cohort, WUE.cohort, by = c("param", "class"))
#beta.params[is.na(beta.params)] <- " "

beta.params <- beta.params %>% arrange(match(param, c("Baseline intercept","Precip", "June Tmax", "DBH")), desc(class))


colnames(beta.params) <- c("Parameter", "Cohort", "Estimate", "95% CI", "Estimate", "95% CI")

# output as a kable table
kable(beta.params, "latex",align=c("c", "c", "l", "c", "l", "c"), booktabs = T, caption = "Parameter Estimates and Model Fit") %>%
  add_header_above(c(" " = 2, "$\\\\delta$ 13C model" = 2, "WUE model" = 2), escape =FALSE) %>%
kable_styling() %>% collapse_rows(1, latex_hline = "major") %>%  footnote(symbol = c("95% CI does not contain zero"), footnote_as_chunk = T)
```

# Okay lets make a d13C and iWUE table for the structureXcohort model estimates

```{r , results="asis", echo = FALSE}
# read in the iWUE and d13 cohort model outputs:
# first iWUE:
WUEparams <- readRDS("/Users/kah/Documents/TreeRings2/outputs/growth_model/iWUE_MAP_TMAX_dbh_cohort/samps.iWUE_struct.cohort.re_struct_cohort_scaled_dataset_v4.rds")
samps <- WUEparams[[1]]
WUE <- samps [,1:16]
#   Modern-Savanna               4
#   Past-Savanna                 3
#   Past-Forest                  1
#   Modern-Forest                2



WUE.m <- melt(WUE)
WUE.cohort.summary <- WUE.m %>% group_by(Var2) %>% dplyr::summarise(mean = mean(value), 
                                       ci.lo = quantile(value, 0.025), 
                                       ci.hi = quantile(value, 0.975))
WUE.cohort <- WUE.cohort.summary %>% separate(Var2, into = c("param", "class"))

# create summary tables of WUE coefficients:
WUE.cohort.summary <- WUE.m %>% group_by(Var2) %>% dplyr::summarise(mean = mean(value), 
                                       Ci.low = quantile(value, 0.025), 
                                       Ci.high = quantile(value, 0.975))
WUE.cohort <- WUE.cohort.summary %>% separate(Var2, into = c("param", "class"))



WUE.cohort$Ci.95 <- paste0("(",round(WUE.cohort$Ci.low, 2), " - ", round(WUE.cohort$Ci.high, 2), ")")
WUE.cohort$mean <- round(WUE.cohort$mean, 3)
WUE.cohort$mean <- ifelse(WUE.cohort$Ci.low < 0 & WUE.cohort$Ci.high< 0, paste(WUE.cohort$mean, "*"),
                                  ifelse(WUE.cohort$Ci.low > 0 & WUE.cohort$Ci.high > 0, paste(WUE.cohort$mean, "*"), WUE.cohort$mean))


#   Modern-Savanna               4
#   Past-Savanna                 3
#   Past-Forest                  1
#   Modern-Forest                2
WUE.cohort$class <- ifelse(WUE.cohort$class %in% 1, "Past-Forest", 
                           ifelse(WUE.cohort$class %in% 2, "Modern-Forest", 
                                  ifelse(WUE.cohort$class %in% 3,"Past-Savanna",
                                         "Modern-Savanna")))
WUE.cohort$param <- ifelse(WUE.cohort$param %in% "beta1", "Baseline Intercept", 
                            ifelse(WUE.cohort$param %in% "beta2", "Precip",
                                   ifelse(WUE.cohort$param %in% "beta3", "June Tmax","DBH")))

WUE.cohort <- WUE.cohort[,c("param", "class", "mean", "Ci.95")]



# now d13C
d13Cparams <- readRDS( "/Users/kah/Documents/TreeRings2/outputs/growth_model/iWUE_MAP_TMAX_dbh_cohort/samps.d13_struct.cohort_struct_cohort_scaled_dataset_v4.rds")
samps <- d13Cparams[[1]]
d13C <- samps[,1:16]


d13C.m <- melt(data.frame(d13C))
colnames(d13C.m)[1] <- "Var2"
d13C.cohort.summary <- d13C.m %>% group_by(Var2) %>% dplyr::summarise(mean = mean(value), 
                                       Ci.low = quantile(value, 0.025), 
                                       Ci.high = quantile(value, 0.975))
d13C.cohort <- d13C.cohort.summary %>% separate(Var2, into = c("param", "class"))



d13C.cohort$Ci.95 <- paste0("(",round(d13C.cohort$Ci.low, 2), " - ", round(d13C.cohort$Ci.high, 2), ")")
d13C.cohort$mean <- round(d13C.cohort$mean, 3)
d13C.cohort$mean <- ifelse(d13C.cohort$Ci.low < 0 & d13C.cohort$Ci.high< 0, paste(d13C.cohort$mean, "*"),
                                  ifelse(d13C.cohort$Ci.low > 0 & d13C.cohort$Ci.high > 0, paste(d13C.cohort$mean, "*"), d13C.cohort$mean))

#   Modern-Savanna               4
#   Past-Savanna                 3
#   Past-Forest                  1
#   Modern-Forest                2
d13C.cohort$class <- ifelse(d13C.cohort$class %in% 1, "Past-Forest", 
                           ifelse(d13C.cohort$class %in% 2, "Modern-Forest", 
                                  ifelse(d13C.cohort$class %in% 3,"Past-Savanna",
                                         "Modern-Savanna")))
d13C.cohort$param <- ifelse(d13C.cohort$param %in% "beta1", "Baseline Intercept", 
                            ifelse(d13C.cohort$param %in% "beta2", "Precip",
                                   ifelse(d13C.cohort$param %in% "beta3", "June Tmax","DBH")))

d13C.cohort <- d13C.cohort[,c("param", "class", "mean", "Ci.95")]


# join the tables together:

beta.params <- merge(d13C.cohort, WUE.cohort, by = c("param", "class"))
#beta.params[is.na(beta.params)] <- " "

beta.params <- beta.params %>% arrange(match(param, c("Baseline Intercept","Precip", "June Tmax", "DBH")), desc(class))


colnames(beta.params) <- c("Parameter", "Cohort", "Estimate", "95% CI", "Estimate", "95% CI")

# output as a kable table
kable(beta.params, "latex",align=c("c", "c", "l", "c", "l", "c"), booktabs = T, caption = "Parameter Estimates and Model Fit") %>%
  add_header_above(c(" " = 2, "$\\\\delta$ 13C model" = 2, "WUE model" = 2), escape =FALSE) %>%
kable_styling() %>% collapse_rows(1, latex_hline = "major") %>%  footnote(symbol = c("95% CI does not contain zero"), footnote_as_chunk = T)
```

