---
title: "KF_tree_rings"
author: "Kelly Heilman"
date: "February 8, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Kalman Filter/Time varying Regression model to estimate tree ring regressions 
code  based off an example from:
<http://lalas.github.io/quantitativeThoughts/r/2014/09/01/dlmTutorial.html#topic2.1>

Here we read in example data
```{r cars}
library(dplR)
Bonanza <- read.tucson("./cofecha/BONww.rwl", header = TRUE)
BON.rwi <- detrend(rwl = Bonanza, method = "Spline")
plot(BON.rwi)
#create chronology of sites
BON.crn <- chron(BON.rwi, prefix = paste('BON'))
plot(BON.crn)

head(BON.crn)

# read in molten df with climate
molten.HIC<- read.csv('data/molten.hic.csv')

```



```{r pressure, echo=FALSE}
library(PerformanceAnalytics, quietly = TRUE,  warn.conflicts = FALSE)
library(dlm)

val <- molten.BON
clim <- "Jul.pdsi"
kalman.plot <- function(val, clim, site.code){
# convert to xts objects
tr<- as.xts(val[,c("value")], order.by = as.yearqtr(val$Year))
pdsi <- as.xts(val[,c( clim )], order.by = as.yearqtr(val$Year))

# Specifying a set model parameters
s2_obs = 1      # Variance of observations
s2_alpha = 0.01 # Variance of the alpha regression parameter
s2_beta = 0.01  # Variance of the beta regression parameter

# Construct a regression model
tvp.dlm = dlmModReg(X=pdsi, addInt=TRUE, dV=s2_obs, dW=c(s2_alpha, s2_beta))

#Now that we have define a model, we can view its different component:

# looking at the various component
tvp.dlm[c("FF","V","GG","W","m0","C0")]
tvp.dlm[c("JFF","JV","JGG","JW")]

#If we were to do a simple linear regression (Ordinary Least Square fit - constant equity beta), we would do something like


ols.fit <- lm(tr ~ pdsi)
summary(ols.fit)

start.vals = c(0,0,0)
# Names ln variance of: observation y, alpha and beta (corresponding intercept and slope of y (tr index) with respect to X (PDSI))
names(start.vals) = c("lns2_obs", "lns2_alpha", "lns2_beta")

# function to build Time Varying Parameter state space model
buildTVP <- function(parm, x.mat){
    parm <- exp(parm)
  return( dlmModReg(X=x.mat, dV=parm[1], dW=c(parm[2], parm[3])) )
}

# Estimate the model
TVP.mle = dlmMLE(y=tr, parm=start.vals, x.mat=pdsi, build=buildTVP, hessian=T)

# get sd estimates
se2 <- sqrt(exp(TVP.mle$par))
names(se2) = c("s_obs", "s_alpha", "s_beta")
sqrt(se2)


# Build fitted ss model, passing to it sp500 as the matrix X in the model
TVP.dlm <- buildTVP(TVP.mle$par, pdsi)
#Filtering and Smooting:
#Filtering Optimal estimates of θtθt given information available at time tt, It={y1,...,yt}It={y1,...,yt}
#Smoothing Optimal estimates of θtθt given information available at time TT, IT={y,...,yT}IT={y,...,yT}
#Now that we have obtained model estimates, and build the optimal model, we can filter the data through it, to obtain filtered values of the state vectors, together with their variance/co-variance matrices.

TVP.f <- dlmFilter(y = tr, mod = TVP.dlm)
#class(TVP.f)

#names(TVP.f)

#Similarly, to obtained the smoothed values of the state vectors, together with their variance/co-variance matrices; using knowledge of the entire series

# Optimal estimates of θ_t given information available at time T.
TVP.s <- dlmSmooth(TVP.f)
#class(TVP.s)



#Plotting the results (smoothed values)
#Now that we have obtained the smoothed values of the state vectors, we can draw them as:



# extract smoothed states - intercept and slope coefs
alpha.s = xts(TVP.s$s[-1,1,drop=FALSE], as.yearqtr( rownames(TVP.s$s[-1,])))

beta.s  = xts(TVP.s$s[-1,2,drop=FALSE], as.yearqtr(rownames(TVP.s$s[-1,])))
colnames(alpha.s) = "alpha"
colnames(beta.s)  = "beta"
#Extracting the std errors and constructing the confidence band

# extract std errors - dlmSvd2var gives list of MSE matrices
mse.list = dlmSvd2var(TVP.s$U.S, TVP.s$D.S)
se.mat = t(sapply(mse.list, FUN=function(x) sqrt(diag(x))))
se.xts = xts(se.mat[-1, ], index(beta.s))
colnames(se.xts) = c("alpha", "beta")
a.u = alpha.s + 1.96*se.xts[, "alpha"]
a.l = alpha.s - 1.96*se.xts[, "alpha"]
b.u = beta.s  + 1.96*se.xts[, "beta"]
b.l = beta.s  - 1.96*se.xts[, "beta"]
#And plotting the results with +/- 2 times the standard deviation
par(mfrow = c(2,1))

# plot smoothed estimates with +/- 2*SE bands
chart.TimeSeries(cbind(alpha.s, a.l, a.u), main=paste("Smoothed estimates of alpha for", site.code), ylim=c(0,2),
                 colorset=c(1,2,2), lty=c(1,2,2),ylab=expression(alpha),xlab="")

chart.TimeSeries(cbind(beta.s, b.l, b.u), main=paste("Smoothed estimates of beta for", site.code),
                 colorset=c(1,2,2), lty=c(1,2,2),ylab=expression(beta),xlab="")


}

X11(width = 12)
kalman.plot(val = molten.UNC, clim = "Jul.pdsi", site.code = "UNC")
kalman.plot(val = molten.BON, clim = "Jul.pdsi", site.code = "BON")
kalman.plot(val = molten.HIC, clim = "Jul.pdsi", site.code = "HIC")
kalman.plot(val = molten.STC, clim = "Jul.pdsi", site.code = "STC")
kalman.plot(val = molten.TOW, clim = "Jul.pdsi", site.code = "TOW")
kalman.plot(val = molten.COR, clim = "Jul.pdsi", site.code = "COR")
kalman.plot(val = molten.ENG, clim = "Jul.pdsi", site.code = "ENG")
```

## compare to moving window correlations:
```{r}
library(treeclim)

# we will us the dcc function in the tree clim package, but this funtion takes monthly data:

#read climate
IL.clim <- read.csv("data/NE_illinois_climdiv.csv") #Hickory Grove, Sandwich, Glacial park
WIse.clim <- read.csv("data/south_east_wi_climdiv.csv") #pleasant prairie 
MNwc.clim <- read.csv("data/West_central_MN_nclimdiv.csv") #Bonanza praire, Duboix
WIsc.clim <- read.csv("data/south_central_WI_climdiv.csv") #pleasant valley conservancy
MNec.clim <- read.csv("data/East_Central_MN_CDODiv5039587215503.csv") #townsend woods 
MNec.clim <- read.csv("data/East_Central_MN_CDODiv5039587215503.csv") #St. Croix savanna
MNse.clim <- read.csv("data/South_East_MN_CDO.csv") # for mound prairie

# We need the raw data:
Glacial <- read.tucson("C:/Users/JMac/Documents/Kelly/crossdating/data/cofecha/GLA.rwl")
Hickory <- read.tucson ("./cofecha/HICww.rwl")
Bonanza <- read.tucson("./cofecha/BONww.rwl")
Pleasant <- read.tucson('./cofecha/PLEww.rwl')
Townsend <- read.tucson('./cofecha/tow/TOWww.rwl')
StCroix <- read.tucson('./cofecha/STCww.rwl')
Coral <- read.tucson('C:/Users/JMac/Documents/Kelly/crossdating/data/cofecha/COR.rwl')
Uncas <- read.tucson("C:/Users/JMac/Documents/Kelly/crossdating/data/cofecha/UNC.rwl")
Englund <- read.tucson("C:/Users/JMac/Documents/Kelly/crossdating/data/cofecha/ENG.rwl")
Mound <- read.tucson("C:/Users/JMac/Documents/Kelly/crossdating/data/cofecha/MOU.rwl")




source("R/read_detrend_rwl.R")

Glacial <- read_detrend_rwl(Glacial, "Glacial")
Hickory <- read_detrend_rwl(Hickory, "Hickory")
Bonanza <- read_detrend_rwl(Bonanza, "Bonanza")
Pleasant <- read_detrend_rwl(Pleasant, "Pleasant")
Townsend <- read_detrend_rwl(Townsend, "Townsend")
StCroix <- read_detrend_rwl(StCroix, "StCroix")
Coral <- read_detrend_rwl(Coral, "Coral")
Uncas <- read_detrend_rwl(Uncas, "Uncas")
Englund <- read_detrend_rwl(Englund, "Englund")
Mound <- read_detrend_rwl(Mound, "Mound")

# moving correlations between climate and tree growth:

a<- dcc(Hickory, IL.clim[1:1452,c("Year", "Month", "PCP")], dynamic = 'moving', win_size = 35, win_offset = 5)
a

plot(a)
traceplot(a)


#these funcitons print out plots time moving correlations for all of the climate parameters

clim.cor<- function(climate, chron, site.name){

PREC <- climate[,c('Year', 'Month', 'PCP')]
PREC$PCP <- PREC$PCP*25.54
PREC <- PREC[1:1452,]


hic.pdsi.static <- dcc(chron, PREC, dynamic = 'static', win_size = 35, win_offset = 5)
pdf(paste0('outputs/correlations/moving_site_cors/PREC_', site.name,'dynamic.pdf'))
print(plot(hic.pdsi.static))
#g_test(hic.pdsi.moving)
#traceplot(hic.pdsi.moving)
#plot(skills(hic.pdsi.moving))


hic.pdsi.moving <- dcc(chron, PREC, dynamic = 'moving', win_size = 35, win_offset = 5)

print(plot(hic.pdsi.moving))
#g_test(hic.pdsi.moving)
print(traceplot(hic.pdsi.moving))
#plot(skills(hic.pdsi.moving))
dev.off()

#PDSI
PDSI <- climate[,c('Year', 'Month', 'PDSI')]

PDSI <- PDSI[1:1452,]

pdf(paste0('outputs/correlations/moving_site_cors/PDSI_', site.name,'dynamic.pdf'))
hic.pdsi.static <- dcc(chron, PDSI, dynamic = 'static', win_size = 35, win_offset = 5)

print(plot(hic.pdsi.static))
#g_test(hic.pdsi.moving)
#traceplot(hic.pdsi.moving)
#plot(skills(hic.pdsi.moving))

hic.pdsi.moving <- dcc(chron, PDSI, dynamic = 'moving', win_size = 35, win_offset = 5)

print(plot(hic.pdsi.moving))
#g_test(hic.pdsi.moving)
print(traceplot(hic.pdsi.moving))
#plot(skills(hic.pdsi.moving))
dev.off()

#TAVG
TAVG <- climate[,c('Year', 'Month', 'TAVG')]

TAVG <- TAVG[1:1452,]

pdf(paste0('outputs/correlations/moving_site_cors/TAVG_', site.name,'dynamic.pdf'))
hic.pdsi.static <- dcc(chron, TAVG, dynamic = 'static', win_size = 35, win_offset = 5)

print(plot(hic.pdsi.static))


hic.pdsi.moving <- dcc(chron, TAVG, dynamic = 'moving', win_size = 35, win_offset = 5)

print(plot(hic.pdsi.moving))
#g_test(hic.pdsi.moving)
print(traceplot(hic.pdsi.moving))
dev.off()


#TMAX
TMAX <- climate[,c('Year', 'Month', 'TMAX')]

TMAX <- TMAX[1:1452,]

pdf(paste0('outputs/correlations/moving_site_cors/TMAX_', site.name,'dynamic.pdf'))
hic.pdsi.static <- dcc(chron, TMAX, dynamic = 'static', win_size = 35, win_offset = 5)

print(plot(hic.pdsi.static))


hic.pdsi.moving <- dcc(chron, TMAX, dynamic = 'moving', win_size = 35, win_offset = 5)

print(plot(hic.pdsi.moving))
#g_test(hic.pdsi.moving)
print(traceplot(hic.pdsi.moving))
#plot(skills(hic.pdsi.moving))
dev.off()

#TMIN
TMIN <- climate[,c('Year', 'Month', 'TMIN')]

TMIN <- TMIN[1:1452,]

pdf(paste0('outputs/correlations/moving_site_cors/TMIN_', site.name,'dynamic.pdf'))
hic.pdsi.static <- dcc(chron, TMIN, dynamic = 'static', win_size = 35, win_offset = 5)

print(plot(hic.pdsi.static))


hic.pdsi.moving <- dcc(chron, TMIN, dynamic = 'moving', win_size = 35, win_offset = 5)

print(plot(hic.pdsi.moving))
#g_test(hic.pdsi.moving)
print(traceplot(hic.pdsi.moving))
#plot(skills(hic.pdsi.moving))
dev.off()
dev.off()
}

clim.cor(IL.clim, Hickory, 'Hickory_Grove_')
clim.cor(MNwc.clim, Bonanza, 'Bonanza_Prairie_')
clim.cor(MNwc.clim, Desoix, 'Desoix_')
clim.cor(WIsc.clim, Pleasant, 'Pleasant_Valley_Conservancy_')
clim.cor(MNec.clim, Townsend, 'Townsend_woods_')
clim.cor(MNec.clim, StCroix, 'StCroix_savanna_')
clim.cor(MNse.clim, Mound, 'Mound_prairie_')


```

