---
title: "summary_tables"
author: "Kelly Heilman"
date: "2/27/2019"
output:
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, results="asis"}
library(xtable)
library(tidyr)
library(dplyr)
library(reshape2)
library(kableExtra)
library(knitr)

# 1. Read in the site level summaries generated during crossdating (these come from my Crossdating Repo & were generated using dplR)


# directory that all the csv files are in
data.dir <- "/Users/kah/Documents/crossdating/data/site_summaries/"

file_names = list.files(data.dir)
full_filenames <- paste0(data.dir, file_names)
summaries <- lapply(full_filenames, read.csv)

summary.table <- do.call(rbind, summaries)
summary.table <- summary.table %>% dplyr::select(site, ntrees, Avg.age, TimeSpan, intercorrelation, AR.mean, eps, rbar.eff)

new.table <- xtable(summary.table)
new.table

colnames(summary.table) <- c("Site", "Trees", "Mean Age", "Time span", "Intercorrelation", "AR", "EPS", "Rbar")
print(xtable(summary.table, align = rep("c", 9)), type="latex", include.rownames = FALSE)

site.list <- c("AVO", "BON", "ENG", "GLA", "GLL1", "GLL2", "GLL3", "MOU", "UNC")

```

# Table 1: Site summaries
```{r, results="asis"}
sites.modeled <- summary.table[summary.table$Site %in% site.list, ]
rownames(sites.modeled) <- NULL
print(xtable(sites.modeled, align = rep("c", 9)), type="latex", include.rownames = FALSE)
```

# Table 2: D13C summaries
```{r, results="asis"}
deltas <- read.csv("/Users/kah/Documents/TreeRings/outputs/stable_isotopes/full_std_suess_corrected_d13C.csv")
deltas <- deltas[!is.na(deltas$d13C_12C_corr),]

samples_per_id <- deltas %>% group_by(site, ID) %>% summarise(n())
print(xtable(samples_per_id, type="latex"))
      
      
samples_per_site <- deltas %>% group_by(site) %>% summarise(n())
print(xtable(samples_per_site, type="latex"), include.rownames = FALSE)
      
      
```


# Table 2: Model summaries for struct x cohort model for dry years
```{r, results="asis"}
# read in tables from the following models run on dry years:

# Mod1 = full model, site int, structure/cohort params, no interaction
# Mod2 = full model, site int, structure/cohort params, no interaction

# read in model fit estimates
summary.sorted <- read.csv("/Users/kah/Documents/TreeRings/outputs/growth_model/data_summary_full.csv")

mod1 <- summary.sorted[summary.sorted$model %in% "lag2_reg_struct_x_cohort_re_t_pr_dry_yrs_site_rs",]
mod2 <- summary.sorted[summary.sorted$model %in% "lag2_reg_struct_x_cohort_re_t_pr_dry_yrs_site_rs_inter",]


# --------read in estimates  + 95% CI for Mod1:
samps <- readRDS("/Users/kah/Documents/TreeRings/outputs/growth_model/lag2_reg_struct_x_cohort_re_t_pr_dry_yrs_site_rs/samps.rds")
test.dry <- readRDS("/Users/kah/Documents/TreeRings/outputs/growth_model/lag2_reg_struct_x_cohort_re_t_pr_dry_yrs_site_rs/test.rds")
train.dry <- readRDS("/Users/kah/Documents/TreeRings/outputs/growth_model/lag2_reg_struct_x_cohort_re_t_pr_dry_yrs_site_rs/train.rds")
#samps[,1:2]

 Yp.samps <- samps[,1:(length(test.dry$RWI))] 
# Yprobe.samps <- Y.probe
 alpha.samps  <- samps[,(length(test.dry$RWI)+1):(length(test.dry$RWI)+ 16)]# one alpha for each of 4 cohort-strcuture groups
 beta2.samps <- samps[,(length(test.dry$RWI)+17):(length(test.dry$RWI)+20)]
 beta3.samps <- samps[,(length(test.dry$RWI)+21):(length(test.dry$RWI)+24)]
 beta4.samps <- samps[,(length(test.dry$RWI)+25):(length(test.dry$RWI)+ 28)]
 beta5.samps <- samps[,(length(test.dry$RWI)+ 29):(length(test.dry$RWI)+ 32)]
 beta6.samps <- samps[,(length(test.dry$RWI)+ 33):(length(test.dry$RWI)+ 36)]
 sigma.samps <- samps[,(length(test.dry$RWI)+ 37)]
 sigma_betas <- samps[,(length(test.dry$RWI)+ 30):(length(test.dry$RWI)+ 35)]

a <- data.frame(alpha.samps)
colnames(a) <- unique(train.dry$site)#[order(unique(train.dry[,c("site", "site.num")])[,2])])
a$num <- rownames(a)
a.m <- melt(a, id.vars=c("num"))
 
b2 <- data.frame(beta2.samps)
colnames(b2) <-c(unique(train.dry$struct.cohort)[order(unique(train.dry[,c("struct.cohort", "struct.cohort.code")])[,2])])
#colnames(b2) <- c(paste0(c(unique(train.dry$struct.cohort))))
b2$num <- rownames(b2)
b2.m <- melt(b2, id.vars=c("num"))

b3 <- data.frame(beta3.samps)
colnames(b3) <- c(unique(train.dry$struct.cohort)[order(unique(train.dry[,c("struct.cohort", "struct.cohort.code")])[,2])])
b3$num <- rownames(b3)
b3.m <- melt(b3, id.vars=c("num"))

b4 <- data.frame(beta4.samps)
colnames(b4) <- c(unique(train.dry$struct.cohort)[order(unique(train.dry[,c("struct.cohort", "struct.cohort.code")])[,2])])
b4$num <- rownames(b4)
b4.m <- melt(b4, id.vars=c("num"))

b5 <- data.frame(beta5.samps)
colnames(b5) <- c(unique(train.dry$struct.cohort)[order(unique(train.dry[,c("struct.cohort", "struct.cohort.code")])[,2])])
b5$num <- rownames(b5)
b5.m <- melt(b5, id.vars=c("num"))

b6 <- data.frame(beta6.samps)
colnames(b6) <- c(unique(train.dry$struct.cohort)[order(unique(train.dry[,c("struct.cohort", "struct.cohort.code")])[,2])])
b6$num <- rownames(b6)
b6.m <- melt(b6, id.vars=c("num"))


# get means and ci for each 
b2.sum <- b2.m %>% group_by(variable) %>% dplyr::summarise(mean.val = mean(value),
                                                   Ci.low = quantile(value, 0.025), 
                                                   Ci.high = quantile(value, 0.975))
b2.sum$variable <- factor(b2.sum$variable, levels = c( "Past-Forest", "Past-Savanna", "Modern-Forest", "Modern-Savanna"))
b2.sum$param <- "MAP"

b3.sum <- b3.m %>% group_by(variable) %>% dplyr::summarise(mean.val = mean(value),
                                                   Ci.low = quantile(value, 0.025), 
                                                   Ci.high = quantile(value, 0.975))
b3.sum$variable <- factor(b3.sum$variable, levels = c( "Past-Forest", "Past-Savanna", "Modern-Forest", "Modern-Savanna"))
b3.sum$param <- "DBH"

b4.sum <- b4.m %>% group_by(variable) %>% dplyr::summarise(mean.val = mean(value),
                                                   Ci.low = quantile(value, 0.025), 
                                                   Ci.high = quantile(value, 0.975))
b4.sum$variable <- factor(b4.sum$variable, levels = c( "Past-Forest", "Past-Savanna", "Modern-Forest", "Modern-Savanna"))
b4.sum$param <- "Lag-1"

b5.sum <- b5.m %>% group_by(variable) %>% dplyr::summarise(mean.val = mean(value),
                                                   Ci.low = quantile(value, 0.025), 
                                                   Ci.high = quantile(value, 0.975))
b5.sum$variable <- factor(b5.sum$variable, levels = c( "Past-Forest", "Past-Savanna", "Modern-Forest", "Modern-Savanna"))
b5.sum$param <- "Lag-2"

b6.sum <- b6.m %>% group_by(variable) %>% dplyr::summarise(mean.val = mean(value),
                                                   Ci.low = quantile(value, 0.025), 
                                                   Ci.high = quantile(value, 0.975))
b6.sum$variable <- factor(b6.sum$variable, levels = c( "Past-Forest", "Past-Savanna", "Modern-Forest", "Modern-Savanna"))
b6.sum$param <- "June Tmax"

all.betas <- rbind( b3.sum, b4.sum, b5.sum, b2.sum, b6.sum)
all.betas$Ci.95 <- paste0("(",round(all.betas$Ci.low, 2), " - ", round(all.betas$Ci.high, 2), ")")
all.betas$mean.val <- round(all.betas$mean.val, 3)
all.betas <- all.betas[,c("param", "variable", "mean.val", "Ci.95")]
colnames(all.betas) <- c("Parameter", "Cohort", "Estimate", "95% CI")

print(xtable(all.betas, align = rep("c", 5)), include.rownames = FALSE)

kable(all.betas, "latex", align = "c", booktabs = T) %>%
kable_styling() %>% collapse_rows(1, latex_hline = "major")


# # --------read in estimates  + 95% CI for Mod:
 samps.mod2 <- readRDS("/Users/kah/Documents/TreeRings/outputs/growth_model/lag2_reg_struct_x_cohort_re_t_pr_dry_yrs_site_rs_inter/samps.rds")
 test.dry <- readRDS("/Users/kah/Documents/TreeRings/outputs/growth_model/lag2_reg_struct_x_cohort_re_t_pr_dry_yrs_site_rs_inter/test.rds")
 train.dry <- readRDS("/Users/kah/Documents/TreeRings/outputs/growth_model/lag2_reg_struct_x_cohort_re_t_pr_dry_yrs_site_rs_inter/train.rds")


 alpha.samps.mod2  <- samps.mod2[,1:9]# one alpha for each of 4 cohort-strcuture groups
 beta2.samps.mod2 <- samps.mod2[,10:13]
 beta3.samps.mod2 <- samps.mod2[,14:17]
 beta4.samps.mod2 <- samps.mod2[,18:21]
 beta5.samps.mod2 <- samps.mod2[,22:25]
 beta6.samps.mod2 <- samps.mod2[,26:29]
 beta7.samps.mod2 <- samps.mod2[,30:33]
 mu_beta.samps.mod2 <- samps.mod2[,34:40]
 sigma.samps.mod2 <- samps.mod2[,36]
 sigma_betas <- samps.mod2[,30:35]
      
 
 a <- data.frame(alpha.samps.mod2)
colnames(a) <- unique(train.dry$site)#[order(unique(train.dry[,c("site", "site.num")])[,2])])
a$num <- rownames(a)
a.m <- melt(a, id.vars=c("num"))
 
b2 <- data.frame(beta2.samps.mod2)
colnames(b2) <-c(unique(train.dry$struct.cohort)[order(unique(train.dry[,c("struct.cohort", "struct.cohort.code")])[,2])])
#colnames(b2) <- c(paste0(c(unique(train.dry$struct.cohort))))
b2$num <- rownames(b2)
b2.m <- melt(b2, id.vars=c("num"))

b3 <- data.frame(beta3.samps.mod2)
colnames(b3) <- c(unique(train.dry$struct.cohort)[order(unique(train.dry[,c("struct.cohort", "struct.cohort.code")])[,2])])
b3$num <- rownames(b3)
b3.m <- melt(b3, id.vars=c("num"))

b4 <- data.frame(beta4.samps.mod2)
colnames(b4) <- c(unique(train.dry$struct.cohort)[order(unique(train.dry[,c("struct.cohort", "struct.cohort.code")])[,2])])
b4$num <- rownames(b4)
b4.m <- melt(b4, id.vars=c("num"))

b5 <- data.frame(beta5.samps.mod2)
colnames(b5) <- c(unique(train.dry$struct.cohort)[order(unique(train.dry[,c("struct.cohort", "struct.cohort.code")])[,2])])
b5$num <- rownames(b5)
b5.m <- melt(b5, id.vars=c("num"))

b6 <- data.frame(beta6.samps.mod2)
colnames(b6) <- c(unique(train.dry$struct.cohort)[order(unique(train.dry[,c("struct.cohort", "struct.cohort.code")])[,2])])
b6$num <- rownames(b6)
b6.m <- melt(b6, id.vars=c("num"))

b7 <- data.frame(beta7.samps.mod2)
colnames(b7) <- c(unique(train.dry$struct.cohort)[order(unique(train.dry[,c("struct.cohort", "struct.cohort.code")])[,2])])
b7$num <- rownames(b7)
b7.m <- melt(b7, id.vars=c("num"))


# get means and ci for each 
b2.sum.mod2 <- b2.m %>% group_by(variable) %>% dplyr::summarise(mean.val = mean(value),
                                                   Ci.low = quantile(value, 0.025), 
                                                   Ci.high = quantile(value, 0.975))
b2.sum.mod2$variable <- factor(b2.sum.mod2$variable, levels = c( "Past-Forest", "Past-Savanna", "Modern-Forest", "Modern-Savanna"))
b2.sum.mod2$param <- "MAP"

b3.sum.mod2 <- b3.m %>% group_by(variable) %>% dplyr::summarise(mean.val = mean(value),
                                                   Ci.low = quantile(value, 0.025), 
                                                   Ci.high = quantile(value, 0.975))
b3.sum.mod2$variable <- factor(b3.sum.mod2$variable, levels = c( "Past-Forest", "Past-Savanna", "Modern-Forest", "Modern-Savanna"))
b3.sum.mod2$param <- "DBH"

b4.sum.mod2 <- b4.m %>% group_by(variable) %>% dplyr::summarise(mean.val = mean(value),
                                                   Ci.low = quantile(value, 0.025), 
                                                   Ci.high = quantile(value, 0.975))
b4.sum.mod2$variable <- factor(b4.sum.mod2$variable, levels = c( "Past-Forest", "Past-Savanna", "Modern-Forest", "Modern-Savanna"))
b4.sum.mod2$param <- "Lag-1"

b5.sum.mod2 <- b5.m %>% group_by(variable) %>% dplyr::summarise(mean.val = mean(value),
                                                   Ci.low = quantile(value, 0.025), 
                                                   Ci.high = quantile(value, 0.975))
b5.sum.mod2$variable <- factor(b5.sum.mod2$variable, levels = c( "Past-Forest", "Past-Savanna", "Modern-Forest", "Modern-Savanna"))
b5.sum.mod2$param <- "Lag-2"

b6.sum.mod2 <- b6.m %>% group_by(variable) %>% dplyr::summarise(mean.val = mean(value),
                                                   Ci.low = quantile(value, 0.025), 
                                                   Ci.high = quantile(value, 0.975))
b6.sum.mod2$variable <- factor(b6.sum.mod2$variable, levels = c( "Past-Forest", "Past-Savanna", "Modern-Forest", "Modern-Savanna"))
b6.sum.mod2$param <- "June Tmax"

b7.sum.mod2 <- b7.m %>% group_by(variable) %>% dplyr::summarise(mean.val = mean(value),
                                                   Ci.low = quantile(value, 0.025), 
                                                   Ci.high = quantile(value, 0.975))
b7.sum.mod2$variable <- factor(b7.sum.mod2$variable, levels = c( "Past-Forest", "Past-Savanna", "Modern-Forest", "Modern-Savanna"))
b7.sum.mod2$param <- "June Tmax x MAP"


all.betas.mod2 <- rbind( b3.sum.mod2, b4.sum.mod2, b5.sum.mod2, b2.sum.mod2, b6.sum.mod2, b7.sum.mod2)
all.betas.mod2$Ci.95 <- paste0("(",round(all.betas.mod2$Ci.low, 2), " - ", round(all.betas.mod2$Ci.high, 2), ")")
all.betas.mod2$mean.val <- round(all.betas.mod2$mean.val, 3)
all.betas.mod2 <- all.betas.mod2[,c("param", "variable", "mean.val", "Ci.95")]
colnames(all.betas.mod2) <- c("Parameter", "Cohort", "Estimate", "95% CI")

print(xtable(all.betas.mod2, align = rep("c", 5)), include.rownames = FALSE)

kable(all.betas.mod2, "latex", booktabs = T) %>%
  
kable_styling() %>% collapse_rows(1, latex_hline = "major") %>% kable_styling(latex_options = c("repeat_header"))


# combine the two tables:

beta.params <- merge(all.betas, all.betas.mod2, by = c("Parameter", "Cohort"), all.y = TRUE)
beta.params[is.na(beta.params)] <- " "

beta.params<- beta.params %>% arrange(match(Parameter, c("DBH", "Lag-1", "Lag-2", "June Tmax", "MAP", "June Tmax x MAP")), desc(Cohort))
colnames(beta.params) <- c("Parameter", "Cohort", "Estimate", "95% CI", "Estimate", "95% CI")

kable(beta.params, "latex", align = "c", booktabs = T) %>%
  add_header_above(c(" " = 2, "Model 1" = 2, "Model 2" = 2)) %>%
kable_styling() %>% collapse_rows(1, latex_hline = "major")

# okay now add the model summaries to the dataframe:
kable(beta.params, "latex", align = "c", booktabs = T) %>%
  add_header_above(c(" " = 2, "Model 1" = 2, "Model 2" = 2)) %>%
kable_styling() %>% collapse_rows(1, latex_hline = "major")


model.stats <- rbind(mod1, mod2)
model.stats$modelname <- c("Model 1", "Model 2")
model.stats$MSE <- round(model.stats$MSE, 3)
model.stats$BIAS <- round(model.stats$BIAS, 3)
model.stats$Rsq <- round(model.stats$Rsq, 3)
model.stats$penalties <- round(model.stats$penalties, 3)
model.stats$deviances <- round(model.stats$deviances, 3)
model.stats$penalized_deviance <- round(model.stats$penalized_deviance, 3)


model.stats <- model.stats[, c("modelname","MSE", "BIAS", "Rsq", "penalties", "deviances", "penalized_deviance")]
model.stats.cols <- t(model.stats)
colnames(model.stats.cols) <- c("Model 1", "Model 2")
model.stats.cols<- data.frame(model.stats.cols)
model.stats.cols$cohort <-  c("modelname", "Mean Sq. Error", "Bias", "R sq", "penalties", "deviances", "penalized deviance")
model.stats.cols$Parameter <- " "
model.stats.cols$Ci.95.x <- " "
model.stats.cols$Ci.95.y <- " "

model.stats.cols <- model.stats.cols %>% filter(!cohort %in% "modelname")

model.statsv <- model.stats.cols[, c("Parameter","cohort", "Model.1","Ci.95.x", "Model.2", "Ci.95.y")]
colnames(model.statsv) <- colnames(beta.params)
beta.full <- rbind( beta.params, model.statsv)
row.names(beta.full) <- NULL



kable(beta.full, "latex", align = "c", booktabs = T, caption = "Parameter Estimates & Model Fit") %>%
  add_header_above(c(" " = 2, "Model 1" = 2, "Model 2" = 2)) %>%
kable_styling() %>% collapse_rows(1, latex_hline = "major") %>% group_rows("Model Fit", 25, 30) %>% row_spec(24, hline_after = TRUE)
```
